title: glebosotov's blog
markdown: kramdown

# for atom feed
author:
  name: glebosotov
  email: gleb.osotov@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true
  static_pages:
    output: true
    permalink: /:collection/:title

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
